name: Build

on:
  push:
    branches:
      - develop
      - feature/presentation/template
    tags:
      - v*

env:
  DOCUMENT_NAME: ElementaryRepresentationTheory_HauptSeminar_Weik
  PRESENTATION_NAME: Presentation/ElementaryRepresentationTheory_HauptSeminar_Weik_Slides

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3
      
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: |
           "${{ env.PRESENTATION_NAME }}.tex"
          
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            "${{ env.DOCUMENT_NAME }}.pdf"
            "${{ env.PRESENTATION_NAME }}.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
